name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Use a matrix strategy to build on different OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }} # Run on the OS specified in the matrix

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build release binary
      run: cargo build --release --verbose

    # Determine binary path and name based on OS
    - name: Set binary path and name
      id: set_paths
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "BINARY_PATH=target/release/git-manager.exe" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=git-manager-windows-amd64.exe" >> $GITHUB_ENV
        elif [ "${{ runner.os }}" == "macOS" ]; then
          echo "BINARY_PATH=target/release/git-manager" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=git-manager-macos-amd64" >> $GITHUB_ENV
        else # Linux
          echo "BINARY_PATH=target/release/git-manager" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=git-manager-linux-amd64" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }} # Use dynamic artifact name
        path: ${{ env.BINARY_PATH }}   # Use dynamic binary path
